# Generated by Django 5.0.6 on 2024-06-30 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
