# Generated by Django 5.0.6 on 2024-07-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='upcoming',
        ),
    ]
